#include "PluginEditor.h"
#include "BinaryData.h"

LowFreqVSTAudioProcessorEditor::LowFreqVSTAudioProcessorEditor(LowFreqVSTAudioProcessor& p)
    : AudioProcessorEditor(&p),
      processorRef(p),
      // BinaryData::KnobFilmstrip_png / _pngSize are auto-generated by
      // juce_add_binary_data() from Assets/KnobFilmstrip.png at build time.
      // 26 frames, as specified by the source filmstrip.
      filmstripLookAndFeel(BinaryData::KnobFilmstrip_png, static_cast<size_t>(BinaryData::KnobFilmstrip_pngSize), 26)
{
    // --- Knobs ---------------------------------------------------------
    for (auto* slider : { &freqSlider, &qSlider, &gainSlider })
    {
        slider->setLookAndFeel(&filmstripLookAndFeel);
        addAndMakeVisible(slider);
    }

    for (auto* label : { &freqLabel, &qLabel, &gainLabel })
    {
        label->setJustificationType(juce::Justification::centred);
        label->setColour(juce::Label::textColourId, juce::Colours::white);
        addAndMakeVisible(label);
    }

    freqAttachment = std::make_unique<SliderAttachment>(processorRef.apvts, ParamIDs::freq, freqSlider);
    qAttachment    = std::make_unique<SliderAttachment>(processorRef.apvts, ParamIDs::q, qSlider);
    gainAttachment = std::make_unique<SliderAttachment>(processorRef.apvts, ParamIDs::gain, gainSlider);

    // --- Filter type dropdown ------------------------------------------
    filterTypeBox.addItemList({ "Low-Pass", "Low-Shelf", "High-Pass" }, 1);
    addAndMakeVisible(filterTypeBox);

    filterTypeLabel.setJustificationType(juce::Justification::centred);
    filterTypeLabel.setColour(juce::Label::textColourId, juce::Colours::white);
    addAndMakeVisible(filterTypeLabel);

    filterTypeAttachment = std::make_unique<ComboBoxAttachment>(
        processorRef.apvts, ParamIDs::filterType, filterTypeBox);

    setSize(480, 320);
}

LowFreqVSTAudioProcessorEditor::~LowFreqVSTAudioProcessorEditor()
{
    for (auto* slider : { &freqSlider, &qSlider, &gainSlider })
        slider->setLookAndFeel(nullptr);
}

void LowFreqVSTAudioProcessorEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colour(0xff2b1620)); // dark wine background, complements the filmstrip colour
    g.setColour(juce::Colours::white);
    g.setFont(juce::Font(20.0f, juce::Font::bold));
    g.drawFittedText("Low Frequency Filter", getLocalBounds().removeFromTop(40), juce::Justification::centred, 1);
}

void LowFreqVSTAudioProcessorEditor::resized()
{
    auto area = getLocalBounds().reduced(20);
    area.removeFromTop(40); // space for the title drawn in paint()

    // Dropdown across the top.
    auto dropdownArea = area.removeFromTop(50);
    filterTypeLabel.setBounds(dropdownArea.removeFromLeft(100));
    filterTypeBox.setBounds(dropdownArea.reduced(0, 10));

    area.removeFromTop(10);

    // Three knobs in a row, each with its label underneath.
    const int knobAreaWidth = area.getWidth() / 3;
    auto layoutKnob = [&](juce::Rectangle<int> column, FilmstripRotarySlider& slider, juce::Label& label)
    {
        auto labelArea = column.removeFromBottom(24);
        slider.setBounds(column.reduced(10));
        label.setBounds(labelArea);
    };

    auto freqCol = area.removeFromLeft(knobAreaWidth);
    auto qCol    = area.removeFromLeft(knobAreaWidth);
    auto gainCol = area;

    layoutKnob(freqCol, freqSlider, freqLabel);
    layoutKnob(qCol, qSlider, qLabel);
    layoutKnob(gainCol, gainSlider, gainLabel);
}
